### ISSUE TITLE
Replace New Contract Address with Fees Implemented

### ISSUE THREAD

**Issue by iafhurtado** [La-DAO/Xocolatl-XOC#36]
Oie @0xdcota , cual es/son las direcciones del contrato nuevo de CDP con las fees activas? Es nomas el de Polygon que se tiene que reemplaazar?

**Comment by 0xdcota** [comment]
Sip solamente en Polygon: aqui dejo la [liga](https://github.com/La-DAO/xocolatl-contracts/blob/dev/whitepaper/xocolatl_whitepaper.md#521-polygon-pos).

**Comment by 0xdcota** [comment]
Las reserva de wstETH y WBTC no las recree porque hace mejor sentido reemplazarlas por otras opciones. A lo mejor en Base.

**Comment by iafhurtado** [comment]
Done 🍫🤖
