### ISSUE TITLE
Centralize All Contract Addresses

### ISSUE THREAD

**Issue by iafhurtado** [La-DAO/Xocolatl-XOC#37]
La applicacion tiene varios componentes que utilizan las mismas direcciones en diferentes lugares.

En la pagina de cdp (app/cdp/components) se utilizan los contratos del Xocolatl, que consisten de:

- House Of Reserve (1 contrato por cada asset)
- House Of Coin (este contrato si es compartido entre todos los HouseOfReserves de su respectiva red)
- Assets Accouuntant (igual 1 para todos los HoR)
- Asset Contract (1 contrato por cada asset)

Como se puede ver en los componentes YourDeposits y DepositTable, se usan esos contratos explicitamente pero tambien existen en 3 redes diferentes: Base, Binance y Polygon.

Aqui estan los addressess de cada uno por red:

### Base:

- House Of Reserves:
-- WETH: [0xfF69E183A863151B4152055974aa648b3165014D](https://basescan.org/address/0xfF69E183A863151B4152055974aa648b3165014D)
-- CBETH:[0x5c4a154690AE52844F151bcF3aA44885db3c8A58](https://basescan.org/address/0x5c4a154690AE52844F151bcF3aA44885db3c8A58)

- House Of Coin: [0x02c531Cd9791dD3A31428B2987A82361D72F9b13](https://basescan.org/address/0x02c531Cd9791dD3A31428B2987A82361D72F9b13)

- Assets Accountant: [0xB93EcD005B6053c6F8428645aAA879e7028408C7](https://basescan.org/address/0xB93EcD005B6053c6F8428645aAA879e7028408C7)

- Asset Contracts:
-- WETH: 0x4200000000000000000000000000000000000006
-- cbETH: 0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22

### Binance:

-House Of Reserves: 
-- WETH: [0xd411BE9A105Ea7701FabBe58C2834b7033EBC203](https://bscscan.com/address/0xd411BE9A105Ea7701FabBe58C2834b7033EBC203)
-- WBNB: [0x070ccE6887E70b75015F948b12601D1E759D2024](https://bscscan.com/address/0x070ccE6887E70b75015F948b12601D1E759D2024)

- House Of Coin: [0x7ed1aCD46dE3a4E63f2D3b0f4fB5532e113a520B](https://bscscan.com/address/0x7ed1acd46de3a4e63f2d3b0f4fb5532e113a520b)

- Assets Accountant: [0xB90996A70C957a1496e349434CF0E030A9f693A4](https://bscscan.com/token/0xb90996a70c957a1496e349434cf0e030a9f693a4)

- Assets Contracts: 
-- WETH: 0x2170ed0880ac9a755fd29b2688956bd959f933f8
-- WBNB: 0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c

### Polygon:

- House Of Reserves:
-- WETH: [0x2718644E0C38A6a1F82136FC31dcA00DFCdF92a3](https://polygonscan.com/address/0x2718644E0C38A6a1F82136FC31dcA00DFCdF92a3)
-- WMATIC: [0xF56293025437Db5C0024a37dfcEc792125d56A48](https://polygonscan.com/address/0xf56293025437db5c0024a37dfcec792125d56a48)
-- MATICX: [0x76CAc0bC384a49485627D2235fE132e3038b45BB](https://polygonscan.com/address/0x76cac0bc384a49485627d2235fe132e3038b45bb)

- House Of Coin: [0x9d29E6b3D75F5e676f91b69284e015C9CEa20533](https://polygonscan.com/address/0x9d29e6b3d75f5e676f91b69284e015c9cea20533)

- Assets Accountant: [0x076b6C91cC7e72286cd01D967A44787d1f3A6432](https://polygonscan.com/address/0x076b6c91cc7e72286cd01d967a44787d1f3a6432)

- Assets Contracts:
-- WETH: 0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619
-- WMATIC: 0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270
-- MATICX: 0xfa68FB4628DFF1028CFEc22b4162FCcd0d45efb6

---------------------------------------------------------------------------------------------------------------

### Lending

En la pagina de Lending (app/lending) se usan menos contratos y ya existe una config mas central para los contratos, talvez la podemos extender para incluir las de CDP, pero te lo dejo a tu criterio @garosan como la veas mas facil.

**Comment by garosan** [comment]
Ok ya vi cómo está la onda, mañana me aviento esto.
