### ISSUE TITLE
Loader in Approve-Deposit flow button

### ISSUE THREAD

**Issue by 0xdcota** [La-DAO/Xocolatl-XOC#43]
In the CDP, the approval-deposit modal you have a typed message indicating the user to wait ~10 seconds between approval and deposit. 

It is probably best to just transtion to a loader for those 10 seconds.
Or a better (maybe more complex) is to display loader until you receive confirmation receipt to change the loader to `Deposit`.

Example of a button "loader"
![image](https://github.com/user-attachments/assets/9142b03c-3c32-4f68-b139-0a5436967b19)

![image](https://github.com/user-attachments/assets/84501335-d856-4868-bd6a-3f988e44772f)

**Comment by iafhurtado** [comment]
Oie @0xdcota ,
Cambie hace poco el flow de aprobar y depositar, y ya esta todo el loading en el boton, crees relevante dejar ese mensaje en el modal para avisar de algo relevante en ese paso o lo quito por ahorita?

**Comment by iafhurtado** [comment]
Hey @0xdcota ,
Actualize el flow del boton para aprobar y depositar en el CPD, checalo cuando tengas tiempo y cierra este issue pls.
